<?php

function dna_menu() {
    $items['dna'] = array(
        'title' => 'DNA Sequencer',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('dna_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['dna_success'] = array(
        'title' => 'DNA Results',
        'page callback' => 'dna_form_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function dna_form() {
    $form['sequence'] = array(

    );
    $form['submit'] = array(

    );
    return $form;
}

function element_validate_base($element) {

}

function dna_form_submit($form, &$form_state) {

}

function sequence($input) {
    
    return $output;
}

function dna_form_success() {

}